export type CursorId = 'cursorLeft' | 'cursorRight';
export type TimerMode = 'timer' | 'setup';
export type CursorMapConfig = Record<CursorId, { xSign: number; ySign: number }>;
export type JoyConStatus = { leftConnected: boolean; rightConnected: boolean };
export type JoyConAttitude = { id: CursorId; roll: number; pitch: number; yaw?: number };
export type JoyConButtonState = { pressed: boolean };
export type JoyConButtonPress = { id: CursorId };
export type DisplayInfo = {
    id: number;
    label?: string;
    size: { width: number; height: number };
    scaleFactor?: number;
};
export type PresentationInfo = { id: string; name: string; isRunning: boolean };
export type BatteryStatus = { isLeft: boolean; level: number };
export type UpdatePointerData = { id: CursorId; x: number; y: number };
export type TimerNotificationConfig = {
    time: number;
    filename: string;
    absolutePath: string;
};
export type CalibrationStatus = { id: string; status: string };

export type ElectronAPI = {
    getOpenPowerPointPresentations: () => Promise<PresentationInfo[]>;
    connectJoyCon: (isLeft: boolean) => void;
    shutdownJoyCon: (isLeft: boolean) => void;
    getMediaFiles: () => Promise<string[]>;
    getMediaBasePath: () => Promise<string>;
    onJoyConStatusUpdate: (callback: (status: JoyConStatus) => void) => void;
    onJoyConAttitude: (callback: (data: JoyConAttitude) => void) => void;
    onJoyConButtonX: (callback: (data: JoyConButtonState) => void) => void;
    onJoyConButtonDown: (callback: (data: JoyConButtonState) => void) => void;
    onJoyConButtonXPressed: (callback: (data: JoyConButtonPress) => void) => void;
    onJoyConButtonDownPressed: (callback: (data: JoyConButtonPress) => void) => void;
    onJoyConButtonPlus: (callback: (data: JoyConButtonState) => void) => void;
    onJoyConButtonPlusPressed: (callback: (data: JoyConButtonPress) => void) => void;
    onJoyConButtonMinusPressed: (callback: (data: JoyConButtonPress) => void) => void;
    onJoyConButtonSrPressed: (callback: (data: JoyConButtonPress) => void) => void;
    onAvailableDisplays: (callback: (displays: DisplayInfo[]) => void) => void;
    setTargetDisplay: (displayId: number) => void;
    launchCursorWindow: (displayId: number | string) => void;
    onLaunchError: (callback: (message: string) => void) => void;
    closeCursorWindow: () => void;
    onCursorWindowOpened: (callback: () => void) => void;
    onCursorWindowClosed: (callback: () => void) => void;
    onAvailablePresentations: (callback: (presentations: PresentationInfo[]) => void) => void;
    setTargetPresentation: (identifier: string) => void;
    startCalibration: () => void;
    onCalibrationStatusUpdate: (callback: (statusInfo: CalibrationStatus) => void) => void;
    onJoyConBatteryStatusUpdate: (callback: (status: BatteryStatus) => void) => void;
    requestJoyConStatus: () => void;
    recenterImu: (id: CursorId) => void;
    onUpdatePointer: (callback: (pos: UpdatePointerData) => void) => void;
    sendCursorMapConfig: (config: CursorMapConfig) => void;
    sendCursorVisibilityUpdate: (id: CursorId, isVisible: boolean) => void;
    sendCountdownInitialValue: (value: number) => void;
    onUpdateCountdownInitialValue: (callback: (value: number) => void) => void;
    onChangeFontSize: (callback: (delta: number) => void) => void;
    toggleTimerWindow: () => void;
    startCountdownTimer: (duration: number) => void;
    onStartCountdown: (callback: (duration: number) => void) => void;
    onTimerMenuNavigate: (callback: (direction: number) => void) => void;
    onTimerMenuSelect: (callback: () => void) => void;
    updateTimerPresets: (presets: number[]) => void;
    onUpdateTimerPresets: (callback: (presets: number[]) => void) => void;
    sendTimerStatus: (isCounting: boolean) => void;
    onSetTimerMode: (callback: (mode: TimerMode) => void) => void;
    hideTimerWindow: () => void;
    sendTimerCountdownUpdate: (remainingTime: number) => void;
    updateTimerNotifications: (configs: TimerNotificationConfig[]) => void;
    onUpdateTimerNotifications: (callback: (configs: TimerNotificationConfig[]) => void) => void;
    toggleMessageWindow: () => void;
    sendMessageText: (text: string) => void;
    onUpdateMessageText: (callback: (text: string) => void) => void;
    onMainTimerUpdate: (callback: (remainingTime: number) => void) => void;
};
