export const storageKeys = {
    countdownInitialValue: 'countdownInitialValue',
    lastDisplayId: 'lastDisplayId',
    messageAlwaysOnTop: 'messageAlwaysOnTop',
    messageFontSize: 'messageFontSize',
    messageHtml: 'messageHtml',
    messageWindowOpacity: 'messageWindowOpacity',
    selectedPresentationTarget: 'selectedPresentationTarget',
    soundMediaDir: 'soundMediaDir',
    soundPlayDelayMs: 'soundPlayDelayMs',
    standalonePadAssignments: 'standalonePadAssignments',
    standalonePadVisible: 'standalonePadVisible',
    timerFontSize: 'timerFontSize',
    timerNotifications: 'timerNotifications',
    timerWindowOpacity: 'timerWindowOpacity',
    timerPresets: 'timerPresets',
    timeAlarmTargetTime: 'timeAlarmTargetTime',
    wifiTimerPanelVisible: 'wifiTimerPanelVisible',
    wifiTimerSettings: 'wifiTimerSettings',
} as const;
