{
    type MainRendererContext = import('../../shared/main-renderer-types').MainRendererContext;

    type MainRendererElementsFactoryApi = {
        createMainRendererElements: () => MainRendererContext['elements'];
    };

    /**
     * Main Window の DOM 要素参照を作成する。
     * @returns DOM 要素参照
     */
    const createMainRendererElements = (): MainRendererContext['elements'] => ({
        displaySelect: document.getElementById('display-select') as HTMLSelectElement,
        cursorToggleBtn: document.getElementById('cursor-toggle-btn') as HTMLButtonElement,
        errorMessageDiv: document.getElementById('error-message') as HTMLElement,
        pointerMoveSpeedInput: document.getElementById('pointer-move-speed') as HTMLInputElement,
        pointerMoveSpeedValue: document.getElementById('pointer-move-speed-value') as HTMLElement,
        pointerGyroDeadzoneInput: document.getElementById('pointer-gyro-deadzone') as HTMLInputElement,
        pointerSettingsResetBtn: document.getElementById('pointer-settings-reset-btn') as HTMLButtonElement,
        mainBatteryStatusLeft: document.getElementById('main-battery-status-left') as HTMLElement,
        mainBatteryStatusRight: document.getElementById('main-battery-status-right') as HTMLElement,
        pptSelect: document.getElementById('ppt-select') as HTMLSelectElement,
        pptRefreshBtn: document.getElementById('ppt-refresh-btn') as HTMLButtonElement,
        calibrateButton: document.getElementById('calibrate-button') as HTMLButtonElement,
        calibrationStatus: document.getElementById('calibration-status') as HTMLElement,
        countdownInitialValueInput: document.getElementById('countdown-initial-value') as HTMLInputElement,
        mainStatusLeftText: document.getElementById('main-status-left-text') as HTMLElement,
        mainStatusRightText: document.getElementById('main-status-right-text') as HTMLElement,
        joyconLeftActionBtn: document.getElementById('joycon-left-action-btn') as HTMLButtonElement,
        joyconRightActionBtn: document.getElementById('joycon-right-action-btn') as HTMLButtonElement,
        presetButtonsContainer: document.getElementById('preset-buttons-container') as HTMLElement,
        presetInputsList: document.getElementById('preset-inputs-list') as HTMLElement,
        addPresetConfigBtn: document.getElementById('add-preset-config-btn') as HTMLButtonElement,
        applyPresetsBtn: document.getElementById('apply-presets-btn') as HTMLButtonElement,
        togglePresetEditBtn: document.getElementById('toggle-preset-edit-btn') as HTMLButtonElement,
        presetEditContainer: document.getElementById('preset-edit-container') as HTMLElement,
        sound1Select: document.getElementById('sound1-select') as HTMLSelectElement,
        sound2Select: document.getElementById('sound2-select') as HTMLSelectElement,
        sound1TimeInput: document.getElementById('sound1-time') as HTMLInputElement,
        sound2TimeInput: document.getElementById('sound2-time') as HTMLInputElement,
        refreshSoundsBtn: document.getElementById('refresh-sounds-btn') as HTMLButtonElement,
        soundFolderSelectBtn: document.getElementById('sound-folder-select-btn') as HTMLButtonElement,
        soundPlayDelayInput: document.getElementById('sound-play-delay') as HTMLInputElement,
        sound1PlayBtn: document.getElementById('sound1-play-btn') as HTMLButtonElement,
        sound2PlayBtn: document.getElementById('sound2-play-btn') as HTMLButtonElement,
        standaloneSoundPadToggleBtn: document.getElementById('standalone-sound-pad-toggle-btn') as HTMLButtonElement,
        standaloneSoundPadContainer: document.getElementById('standalone-sound-pad-container') as HTMLElement,
        standaloneSoundPadGrid: document.getElementById('standalone-sound-pad-grid') as HTMLElement,
        sound1RumbleToggle: document.getElementById('sound1-rumble') as HTMLInputElement,
        sound2RumbleToggle: document.getElementById('sound2-rumble') as HTMLInputElement,
        timeAlarmEnabledInput: document.getElementById('time-alarm-enabled') as HTMLInputElement,
        timeAlarmTargetTimeInput: document.getElementById('time-alarm-target-time') as HTMLInputElement,
        toggleTimerWindowBtn: document.getElementById('toggle-timer-window-btn') as HTMLButtonElement,
        showClockTimerBtn: document.getElementById('show-clock-timer-btn') as HTMLButtonElement,
        toggleTimerPauseBtn: document.getElementById('toggle-timer-pause-btn') as HTMLButtonElement,
        addMinuteMainBtn: document.getElementById('add-minute-main-btn') as HTMLButtonElement,
        wifiTimerEnabledInput: document.getElementById('wifi-timer-enabled') as HTMLInputElement,
        wifiTimerIpAddressInput: document.getElementById('wifi-timer-ip-address') as HTMLInputElement,
        wifiTimerPanelContainer: document.getElementById('wifi-timer-panel-container') as HTMLElement,
        wifiTimerPanelToggleBtn: document.getElementById('wifi-timer-panel-toggle-btn') as HTMLButtonElement,
        wifiTimerRefreshBtn: document.getElementById('wifi-timer-refresh-btn') as HTMLButtonElement,
        wifiTimerStateLabel: document.getElementById('wifi-timer-state') as HTMLElement,
        wifiTimerIpLabel: document.getElementById('wifi-timer-current-ip') as HTMLElement,
        wifiTimerCurrentSsidLabel: document.getElementById('wifi-timer-current-ssid') as HTMLElement,
        wifiTimerActiveBrightnessInput: document.getElementById('wifi-timer-active-brightness') as HTMLInputElement,
        wifiTimerIdleBrightnessInput: document.getElementById('wifi-timer-idle-brightness') as HTMLInputElement,
        wifiTimerRotate180Input: document.getElementById('wifi-timer-rotate180') as HTMLInputElement,
        wifiTimerStage1SecondsInput: document.getElementById('wifi-timer-stage1-seconds') as HTMLInputElement,
        wifiTimerStage2SecondsInput: document.getElementById('wifi-timer-stage2-seconds') as HTMLInputElement,
        wifiTimerStage3SecondsInput: document.getElementById('wifi-timer-stage3-seconds') as HTMLInputElement,
        wifiTimerBlinkSecondsInput: document.getElementById('wifi-timer-blink-seconds') as HTMLInputElement,
        wifiTimerBlinkIntervalMsInput: document.getElementById('wifi-timer-blink-interval-ms') as HTMLInputElement,
        wifiTimerStage1ColorInput: document.getElementById('wifi-timer-stage1-color') as HTMLInputElement,
        wifiTimerStage2ColorInput: document.getElementById('wifi-timer-stage2-color') as HTMLInputElement,
        wifiTimerStage3ColorInput: document.getElementById('wifi-timer-stage3-color') as HTMLInputElement,
        wifiTimerAlertColorInput: document.getElementById('wifi-timer-alert-color') as HTMLInputElement,
        wifiTimerApplyDisplayBtn: document.getElementById('wifi-timer-apply-display-btn') as HTMLButtonElement,
        wifiTimerSaveColorEffectBtn: document.getElementById('wifi-timer-save-color-effect-btn') as HTMLButtonElement,
        wifiTimerPresetColorEffectBtn: document.getElementById('wifi-timer-preset-color-effect-btn') as HTMLButtonElement,
        wifiTimerColorEffectPreview: document.getElementById('wifi-timer-color-effect-preview') as HTMLElement,
        wifiTimerToneKindSelect: document.getElementById('wifi-timer-tone-kind') as HTMLSelectElement,
        wifiTimerCurrentCustomToneHint: document.getElementById('wifi-timer-current-custom-tone-hint') as HTMLElement,
        wifiTimerVolumeInput: document.getElementById('wifi-timer-volume') as HTMLInputElement,
        wifiTimerRepeatCountInput: document.getElementById('wifi-timer-repeat-count') as HTMLInputElement,
        wifiTimerCustomSpeedInput: document.getElementById('wifi-timer-custom-speed') as HTMLInputElement,
        wifiTimerApplyAudioBtn: document.getElementById('wifi-timer-apply-audio-btn') as HTMLButtonElement,
        wifiTimerTestAudioBtn: document.getElementById('wifi-timer-test-audio-btn') as HTMLButtonElement,
        wifiTimerCustomToneFileInput: document.getElementById('wifi-timer-custom-tone-file') as HTMLInputElement,
        wifiTimerUploadCustomToneBtn: document.getElementById('wifi-timer-upload-custom-tone-btn') as HTMLButtonElement,
        wifiTimerRefreshCustomToneBtn: document.getElementById('wifi-timer-refresh-custom-tone-btn') as HTMLButtonElement,
        wifiTimerCustomStorageInfo: document.getElementById('wifi-timer-custom-storage-info') as HTMLElement,
        wifiTimerCustomToneList: document.getElementById('wifi-timer-custom-tone-list') as HTMLElement,
        wifiTimerLocalAudioFileInput: document.getElementById('wifi-timer-local-audio-file') as HTMLInputElement,
        wifiTimerStreamAudioBtn: document.getElementById('wifi-timer-stream-audio-btn') as HTMLButtonElement,
        wifiTimerPauseStreamBtn: document.getElementById('wifi-timer-pause-stream-btn') as HTMLButtonElement,
        wifiTimerResumeStreamBtn: document.getElementById('wifi-timer-resume-stream-btn') as HTMLButtonElement,
        wifiTimerCancelStreamBtn: document.getElementById('wifi-timer-cancel-stream-btn') as HTMLButtonElement,
        wifiTimerStreamStatus: document.getElementById('wifi-timer-stream-status') as HTMLElement,
        wifiTimerWifiRefreshBtn: document.getElementById('wifi-timer-wifi-refresh-btn') as HTMLButtonElement,
        wifiTimerWifiProfileSelect: document.getElementById('wifi-timer-profile-select') as HTMLSelectElement,
        wifiTimerConnectProfileBtn: document.getElementById('wifi-timer-connect-profile-btn') as HTMLButtonElement,
        wifiTimerDeleteProfileBtn: document.getElementById('wifi-timer-delete-profile-btn') as HTMLButtonElement,
        wifiTimerMoveUpProfileBtn: document.getElementById('wifi-timer-move-up-profile-btn') as HTMLButtonElement,
        wifiTimerMoveDownProfileBtn: document.getElementById('wifi-timer-move-down-profile-btn') as HTMLButtonElement,
        wifiTimerSsidInput: document.getElementById('wifi-timer-ssid') as HTMLInputElement,
        wifiTimerPasswordInput: document.getElementById('wifi-timer-password') as HTMLInputElement,
        wifiTimerSaveProfileBtn: document.getElementById('wifi-timer-save-profile-btn') as HTMLButtonElement,
        wifiTimerUpdateProfileBtn: document.getElementById('wifi-timer-update-profile-btn') as HTMLButtonElement,
        wifiTimerRebootBtn: document.getElementById('wifi-timer-reboot-btn') as HTMLButtonElement,
        wifiTimerOperationMessage: document.getElementById('wifi-timer-operation-message') as HTMLElement,
        mainCountdownDisplay: document.getElementById('main-countdown-display') as HTMLElement,
        messageInput: document.getElementById('message-input') as HTMLDivElement,
        messageAlwaysOnTopInput: document.getElementById('message-always-on-top') as HTMLInputElement,
        toggleMessageButton: document.getElementById('toggle-message-button') as HTMLButtonElement,
        colorContextMenu: document.getElementById('color-context-menu') as HTMLDivElement,
        
    });

    const root = globalThis as typeof globalThis & {
        mainRendererElementsFactory?: MainRendererElementsFactoryApi;
    };
    root.mainRendererElementsFactory = { createMainRendererElements };
}
